remote_theme: "owasp/www--site-theme@main"
plugins:
 - jekyll-include-cache-0.2.0

tabs:
  - name: Main
    path: index.md
  - name: About Us
    path: tab_about.md
  - name: Next Event
    path: tab_nextevent.md
  - name: Past Events
    path: tab_past_events.md
  - name: Leadership
    path: leaders.md
